services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: entvas-postgres-prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-entvas_db}
      POSTGRES_USER: ${POSTGRES_USER:-entvas_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-entvas_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - entvas-network

    restart: unless-stopped

  # API Server
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: runner
    container_name: entvas-api-prod
    env_file:
      - ./api/.env
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-8000}
      DATABASE_URL: postgresql://${POSTGRES_USER:-entvas_user}:${POSTGRES_PASSWORD:-entvas_password}@postgres:5432/${POSTGRES_DB:-entvas_db}
      LOG_LEVEL: ${LOG_LEVEL:-warn}
    depends_on:
      - postgres
    networks:
      - entvas-network
    restart: unless-stopped


  # Client Application
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: runner
    container_name: entvas-client-prod
    env_file:
      - ./client/.env.local
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL:-ws://localhost:8000}
      NEXT_PUBLIC_RECONNECT_INTERVAL: ${NEXT_PUBLIC_RECONNECT_INTERVAL:-10000}
    depends_on:
      - api
    networks:
      - entvas-network
    restart: unless-stopped


  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: entvas-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - api
      - client
    networks:
      - entvas-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  entvas-network:
    driver: bridge 