services:
  # PostgreSQL Database
  postgres:
    build:
      context: ./services/postgres
      dockerfile: Dockerfile
    container_name: entvas-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-entvas_db}
      POSTGRES_USER: ${POSTGRES_USER:-entvas_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-entvas_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - entvas-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-entvas_user} -d ${POSTGRES_DB:-entvas_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # API Server
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
      target: runner
    container_name: entvas-api
    ports:
      - "8000:8000"
    env_file:
      - ./services/api/.env.production
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-8000}
      DATABASE_URL: postgresql://${POSTGRES_USER:-entvas_user}:${POSTGRES_PASSWORD:-entvas_password}@postgres:5432/${POSTGRES_DB:-entvas_db}
      LOG_LEVEL: ${LOG_LEVEL:-warn}
      AUTH_PROVIDER: ${AUTH_PROVIDER:-auth0}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE:-https://joe-estrella.us.auth0.com/api/v2/}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN:-joe-estrella.us.auth0.com}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID:-Wd1t5JLE8OMxtFV0qv2IZ2URagwb0S7V}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET:-NgVmRHtUrgpCcCfYGbPKUEGTM3KppLQN0wFFtM3ZL_aBZ4u1-rOfeckFETZBGhs3}
      AUTH0_CALLBACK_URL: ${AUTH0_CALLBACK_URL:-http://localhost}
      WEBHOOK_API_KEY: ${WEBHOOK_API_KEY:-entvas_webhook_secret_key_8797f88b5f2e10fbf09d7ef162ffc75b}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - entvas-network
    restart: unless-stopped

  # Client Application
  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
      target: runner
    container_name: entvas-client
    env_file:
      - ./services/client/.env.production
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL:-ws://localhost/ws}
      NEXT_PUBLIC_RECONNECT_INTERVAL: ${NEXT_PUBLIC_RECONNECT_INTERVAL:-10000}
      NEXT_PUBLIC_AUTH0_DOMAIN: ${NEXT_PUBLIC_AUTH0_DOMAIN:-joe-estrella.us.auth0.com}
      NEXT_PUBLIC_AUTH0_CLIENT_ID: ${NEXT_PUBLIC_AUTH0_CLIENT_ID:-Wd1t5JLE8OMxtFV0qv2IZ2URagwb0S7V}
      NEXT_PUBLIC_AUTH0_AUDIENCE: ${NEXT_PUBLIC_AUTH0_AUDIENCE:-https://joe-estrella.us.auth0.com/api/v2/}
      NEXT_PUBLIC_AUTH0_REDIRECT_URI: ${NEXT_PUBLIC_AUTH0_REDIRECT_URI:-http://localhost}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost}
    depends_on:
      - api
    networks:
      - entvas-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    container_name: entvas-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - client
    networks:
      - entvas-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  entvas-network:
    driver: bridge 