app = "entvas-api"
primary_region = "sin"

[build]
dockerfile = "./Dockerfile"

[env]
PORT = "8000"
NODE_ENV = "production"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512

[metrics]
port = 9091
path = "/metrics"

[health_check]
interval = "30s"
timeout = "10s"
start_period = "30s"
retries = 3
