app = "entvas-client"
primary_region = "sin"

[build]
dockerfile = "./Dockerfile"

[env]
PORT = "3000"

[build.args]
  NEXT_PUBLIC_AUTH0_DOMAIN = "joe-estrella.us.auth0.com"
  NEXT_PUBLIC_AUTH0_CLIENT_ID = "Wd1t5JLE8OMxtFV0qv2IZ2URagwb0S7V"
  NEXT_PUBLIC_AUTH0_REDIRECT_URI = "https://entvas-client.fly.dev"
  NEXT_PUBLIC_AUTH0_AUDIENCE = "https://joe-estrella.us.auth0.com/api/v2/"
  NEXT_PUBLIC_API_URL = "https://entvas-api.fly.dev"
  NEXT_PUBLIC_WS_URL = "wss://entvas-api.fly.dev"
  NEXT_PUBLIC_RECONNECT_INTERVAL = "5000"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
